packages/lb-annotation/src/core/toolOperation/checkOperation.ts
View the sequence number display supported by PolygonTool in mode
=> feat:View the sequence number display supported by PolygonTool in mode

packages/lb-annotation/src/core/toolOperation/ViewOperation.ts, packages/lb-annotation/src/types/tool/annotationView.d.ts, packages/lb-components/docs/annotationView.md, packages/lb-components/docs/renderEnhance.md, packages/lb-demo/src/mock/index.js
Provide rendering enhancement capability for data. When you are not satisfied with the current rendering situation and want to expand by yourself, renderenhance provides you with all possible attributes and data, which will be executed every time you get rendering, so you need to pay attention to the execution time and performance of renderenhance to avoid jamming.
=> feat: add renderEnhance function

packages/lb-annotation/package.json, packages/lb-annotation/src/core/toolOperation/ViewOperation.ts, packages/lb-annotation/src/core/toolOperation/pointOperation.ts, packages/lb-annotation/src/locales/constants.ts, packages/lb-annotation/src/locales/en_US/message.ts, packages/lb-annotation/src/locales/zh_CN/message.ts, packages/lb-annotation/src/types/tool/annotationView.d.ts, packages/lb-annotation/src/utils/tool/DrawUtils.ts, packages/lb-annotation/src/utils/tool/PolygonUtils.ts, packages/lb-components/package.json
[feat: AnntoationView-Polygon adds keypoint showing](https://github.com/open-mmlab/labelbee/commit/f414dab0cec2ce09f14cf7af22272632d9717c17)
[feat: PointTool emits messageSuccess when it adsorb edge](https://github.com/open-mmlab/labelbee/commit/e643dca72a7e3bcff45549d63ac3c2af67bb7dc2)
=> SenseBee Feature

packages/lb-components/src/components/videoPlayer/TagToolInstanceAdaptor.tsx, packages/lb-components/src/components/videoPlayer/components/controller/index.tsx, packages/lb-components/src/components/videoPlayer/index.tsx, packages/lb-components/src/components/videoPlayer/utils.ts, packages/lb-components/src/store/annotation/reducer.ts, packages/lb-components/src/views/MainView/toolFooter/FooterTips/ToolHotKey/index.tsx
- Fix: VideoPlayer have error status while src changed
- Fix: Eslint errors
- Feat: VideoPlayer playPause while video clicked
=> VideoPlayer features && Eslint error

packages/lb-components/src/components/pointCloudView/PointCloudLayout.tsx, packages/lb-components/src/components/pointCloudView/index.tsx, packages/lb-components/src/index.scss, packages/lb-components/src/store/annotation/reducer.ts
=> feat: Add PointCloudLayout for point-cloud components

packages/lb-demo/package.json, packages/lb-utils/package.json
lb-utils needs to be initialized when the user first starts
=> chore: Fix initialization startup error

packages/lb-annotation/src/core/index.ts, packages/lb-annotation/src/core/scheduler.ts, packages/lb-annotation/src/core/toolOperation/basicToolOperation.ts, packages/lb-annotation/src/core/toolOperation/segmentByRect.ts, packages/lb-components/src/components/customResizeHook/index.tsx, packages/lb-components/src/views/MainView/sidebar/SwitchAttributeList/index.tsx, packages/lb-components/src/views/MainView/toolFooter/ZoomController/ZoomLevel/index.tsx, packages/lb-demo/README.md, packages/lb-demo/src/mock/index.js, packages/lb-demo/src/mock/taskConfig.js
Add ToolScheduler to switch different tool
=> feat: Upgrade Annotation Engine

packages/lb-annotation/src/core/toolOperation/pointOperation.ts, packages/lb-components/src/components/pointCloudView/hooks/useHistory.ts, packages/lb-components/src/components/pointCloudView/hooks/usePointCloudViews.ts, packages/lb-components/src/components/pointCloudView/hooks/useSphere.ts, packages/lb-components/src/components/pointCloudView/hooks/useStatus.ts, packages/lb-components/src/views/MainView/toolFooter/AnnotatedAttributes/index.tsx
1.avoid setting empty defautAttribute when canceling active status
2.add sphereList into display list in annotated attributes
3.update sphere history in 3d view when undoing in point tool
=> fix bugs in pointcloud about point tool

packages/lb-annotation/src/core/scheduler.ts, packages/lb-components/src/components/pointCloudView/PointCloudTopView.tsx, packages/lb-utils/src/constant/pointCloud.ts
1.support zoom event when there is a remark layer
2.sync zoom levels in different tools when dragging
3.change the default size of sphere in 3d view
=> Fix bugs in pointcloud about point tools

packages/lb-annotation/src/core/pointCloud/annotation.ts, packages/lb-annotation/src/core/scheduler.ts, packages/lb-components/src/components/pointCloudView/PointCloudListener.tsx, packages/lb-components/src/components/pointCloudView/PointCloudTopView.tsx, packages/lb-components/src/components/pointCloudView/hooks/useHistory.ts, packages/lb-components/src/components/pointCloudView/hooks/usePointCloudViews.ts, packages/lb-components/src/components/pointCloudView/hooks/useSphere.ts, packages/lb-components/src/views/MainView/toolHeader/headerOption/index.tsx
1.copy backward result doesn't work
2.support switching active point in point tool
3.sync drag move when there is remark layer
4.support undo and redo in point tool
=> Fix bugs in pointcloud point tool

packages/lb-annotation/package.json, packages/lb-annotation/src/core/pointCloud/index.ts, packages/lb-components/package.json, packages/lb-components/src/components/pointCloudView/PointCloud3DView.tsx, packages/lb-components/src/components/pointCloudView/PointCloudBackView.tsx, packages/lb-components/src/components/pointCloudView/PointCloudContext.tsx, packages/lb-components/src/components/pointCloudView/PointCloudInfos.tsx, packages/lb-components/src/components/pointCloudView/PointCloudListener.tsx, packages/lb-components/src/components/pointCloudView/PointCloudSideView.tsx, packages/lb-components/src/components/pointCloudView/PointCloudTopView.tsx, packages/lb-components/src/components/pointCloudView/components/PointCloudSizeSlider/index.tsx, packages/lb-components/src/components/pointCloudView/hooks/useRotate.ts, packages/lb-components/src/index.scss, packages/lb-components/src/views/MainView/sidebar/PointCloudToolSidebar/index.tsx, packages/lb-demo/package.json, packages/lb-utils/package.json, packages/lb-utils/src/annotation/ResourceManager.ts, packages/lb-utils/src/index.ts
[feat(pointcloud-box-info): Update the position of boxInfoShow](https://github.com/open-mmlab/labelbee/commit/8c77c1703f3c1f846ca9ea74cc3805f198a91bf5)
[feat(pointcloud-sidebar): Update the sort of component](https://github.com/open-mmlab/labelbee/commit/aca084c5afa037631eed00c206a15505727e175d)
=> PointCloud-hotfixUpdate

packages/lb-annotation/src/core/pointCloud/index.ts, packages/lb-components/src/components/AnnotationView/pointCloudAnnotationView.tsx, packages/lb-components/src/components/pointCloudView/PointCloudContext.tsx, packages/lb-components/src/components/pointCloudView/PointCloudSegmentListener.tsx, packages/lb-components/src/components/pointCloudView/hooks/useHistory.ts, packages/lb-components/src/components/pointCloudView/hooks/usePointCloudViews.ts, packages/lb-components/src/components/pointCloudView/hooks/useSingleBox.ts, packages/lb-components/src/components/pointCloudView/hooks/useSphere.ts, packages/lb-components/src/components/pointCloudView/hooks/useStatus.ts, packages/lb-components/src/components/pointCloudView/index.tsx, packages/lb-components/src/components/predictTracking/previewResult/index.tsx, packages/lb-utils/src/PointCloudUtils.ts
This way will affect the delection of box & point
=> feat(pointcloud): Move the pointCloudData to pointCloudView/index.tsx

packages/lb-annotation/src/core/pointCloud/index.ts, packages/lb-annotation/src/core/toolOperation/polygonOperation.ts, packages/lb-components/src/components/pointCloudView/PointCloud3DView.tsx
1. Clear all dragging Status after mouse leave.
=> fix(pointcloud): Width and Height become negative after dragging

packages/lb-components/src/components/pointCloudView/components/HighlightVisible/index.tsx, packages/lb-components/src/components/pointCloudView/hooks/usePointCloudViews.ts, packages/lb-components/src/index.scss
1. [fix(pointcloud): Wrong highlightColor after sideView update](https://github.com/open-mmlab/labelbee/commit/e5696a1e145219fe9f03469de7a0fcf21b8def9c)
2. [fix(pointcloud-visible): Hide the hightlightEye when enlarge 2D image](https://github.com/open-mmlab/labelbee/commit/2dcd379192b64a03210692a4fbcc18b1eaaef6c6)
=> Fix the highlight Error

packages/lb-annotation/src/core/toolOperation/pointCloud2dOperation.ts, packages/lb-annotation/src/core/toolOperation/polygonOperation.ts, packages/lb-components/src/components/pointCloudView/PointCloudListener.tsx, packages/lb-components/src/components/pointCloudView/hooks/usePointCloudViews.ts
[fix: When useing defaultSize vaild should be true](https://github.com/open-mmlab/labelbee/commit/38d4b3609c04732c12c2de5dbb1bcd3b38cfcef5)
[fix: Resolve bug when updating validity on top view](https://github.com/open-mmlab/labelbee/commit/1ee685d51d4487b2b2cf95198df63c9756b562cc)
[feat: When changing the attribute perform the preDataProcess operation](https://github.com/open-mmlab/labelbee/commit/76b6c6fd7a98806c903089a3fb3ce10bd4a638b5)
=> feat: When changing the attribute perform the preDataProcess operation

packages/lb-annotation/src/core/pointCloud/annotation.ts, packages/lb-annotation/src/core/scheduler.ts
Need to resize the size of dom & canvas in topview
=> fix(pointcloud): Showing line&point Error after resizing

packages/lb-annotation/src/core/toolOperation/basicToolOperation.ts
From image-based to screen based
=> fix: Change the zoom minimum size

packages/lb-annotation/src/core/toolOperation/rectOperation.ts, packages/lb-annotation/src/types/tool/rectTool.d.ts
sync highlight same textAttr rect of selected rect
=> sync highlight same textAttr rect of selected rect

packages/lb-components/src/components/pointCloudView/PointCloudContext.tsx, packages/lb-components/src/components/pointCloudView/PointCloudListener.tsx, packages/lb-components/src/components/pointCloudView/PointCloudTopView.tsx, packages/lb-components/src/index.scss, packages/lb-components/src/index.tsx, packages/lb-components/src/store/annotatedBox/index.tsx, packages/lb-components/src/views/MainView/sidebar/PointCloudToolSidebar/components/findTrackIDIndex/index.module.scss, packages/lb-components/src/views/MainView/sidebar/PointCloudToolSidebar/components/rectRotateSensitivitySlider/index.module.scss, packages/lb-components/src/views/MainView/sidebar/PointCloudToolSidebar/components/rectRotateSensitivitySlider/index.tsx, packages/lb-components/src/views/MainView/sidebar/PointCloudToolSidebar/index.tsx, packages/lb-utils/src/i18n/resources.json
找回这个 
[pr](https://github.com/open-mmlab/labelbee/pull/471)
=> feat: add RectRotateSensitivitySlider to siderbar

packages/lb-components/src/components/AnnotationView/index.tsx, packages/lb-components/src/components/pointCloudView/PointCloud2DSingleView.tsx, packages/lb-components/src/components/pointCloudView/PointCloud2DView.tsx, packages/lb-components/src/types/data.d.ts
添加 camera.image.processedUrl  为首选, camera.image.url 为 fallback url, 对应 labelbee 修改
=> feat: add fallback url to AnnotationView

packages/lb-annotation/src/core/pointCloud/index.ts, packages/lb-components/src/components/pointCloud2DRectOperationView/index.tsx, packages/lb-components/src/components/pointCloudView/PointCloud2DSingleView.tsx, packages/lb-components/src/components/pointCloudView/PointCloudContext.tsx, packages/lb-components/src/components/pointCloudView/PointCloudSegment2DView.tsx, packages/lb-components/src/components/pointCloudView/hooks/useHighlight.ts
修复了优先使用 webp 格式图片导致的2d 框图片/高亮点云功能/分割模式的图片加载问题
=> feat: fix a loading error when using webp images first in 2D highlights cloud

packages/lb-annotation/src/core/toolOperation/pointCloud2DRectOperation.ts, packages/lb-annotation/src/core/toolOperation/rectOperation.ts, packages/lb-components/src/components/pointCloud2DRectOperationView/index.tsx, packages/lb-components/src/components/pointCloudView/PointCloud2DSingleView.tsx, packages/lb-components/src/components/pointCloudView/PointCloudContext.tsx, packages/lb-components/src/components/pointCloudView/PointCloudListener.tsx, packages/lb-components/src/components/pointCloudView/hooks/useDataLinkSwitch.tsx, packages/lb-components/src/components/pointCloudView/hooks/useSingleBox.ts, packages/lb-components/src/components/pointCloudView/utils/map.ts, packages/lb-components/src/index.tsx, packages/lb-components/src/views/MainView/toolFooter/BatchSwitchConnectIn2DView/BatchSwitchConnectIn2DView.tsx, packages/lb-components/src/views/MainView/toolFooter/BatchSwitchConnectIn2DView/index.ts, packages/lb-utils/src/i18n/resources.json
1. Add batch connect/disconnect opertaion
2. Fix typescript typing problem
=> feat: Add batch connnect/disconnect operation

packages/lb-annotation/src/core/toolOperation/rectOperation.ts, packages/lb-annotation/src/core/toolOperation/utils/reCalcRect.ts
fix: width and height <100 to reizeRect, 
fix: and adjust coordinate order
=> feat: Fix width and height <100 to reizeRect, and adjust coordinate

packages/lb-annotation/src/core/pointCloud/index.ts, packages/lb-components/src/utils/ToolPointCloudBoxRenderHelper.ts
fix the color rendering lag when only one box
=> fix: the color rendering lag when only one box

packages/lb-annotation/src/core/toolOperation/ViewOperation.ts, packages/lb-components/src/components/audioPlayer/clipRegion/index.module.scss, packages/lb-components/src/components/audioPlayer/clipRegion/index.tsx
This reverts commit 96b4b859b114d9e77a976e9c1e531702576ba6f5.
=> Revert "feat: Audio tool secondary attribute optimizatio"

packages/lb-annotation/src/core/pointCloud/index.ts, packages/lb-components/src/components/pointCloudView/PointCloud2DSingleView.tsx, packages/lb-components/src/components/pointCloudView/PointCloudContext.tsx, packages/lb-components/src/components/pointCloudView/PointCloudInfos.tsx, packages/lb-components/src/components/pointCloudView/components/HighlightVisible/index.tsx, packages/lb-components/src/components/pointCloudView/hooks/usePointCloudViews.ts, packages/lb-components/src/index.scss
fix: no need highlight render async when add box
fix: toggle2dVisible status confusion
fix: optimize drag and drop experience for back and side views
=> fix: optimize the experience of toggle2dVisible / add box / drag edge in back and side views

packages/lb-components/src/components/pointCloudView/PointCloudBackView.tsx, packages/lb-components/src/components/pointCloudView/PointCloudLayout.tsx, packages/lb-components/src/components/pointCloudView/PointCloudSideView.tsx, packages/lb-components/src/index.scss
fix: the zoom in button is not clickable in the 2D map area.
=> fix: the zoom in button is not clickable in the 2D map area.

packages/lb-components/src/components/pointCloudView/PointCloudContext.tsx
=> fix: highlight 2D failure

packages/lb-components/src/components/pointCloudView/PointCloudContext.tsx
Due to the side effects caused by useEffect, the variable did not respond in a timely manner, so the modification was rolled back
The operation delay issue has been fixed by ae7720fa9190d63e6229beee951c66560a077cd6, so there are no other impacts
=> fix:  ptCtx responsive
